apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database-container
          image: muhammadbilalarshad/passwordmanager
          volumeMounts:
            - name: database-storage
              mountPath: /data/db  
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pvc
